### PR TITLE
Fix callback in release build (#50)

### PR DESCRIPTION
**Pull request by sanak**
@Yukams, @moovida
#50 release build problem (crash at callback) was reproducible also in this example app with the following steps.
1. Add the following changes
   - commit diff: https://github.com/Yukams/background_locator_fixed/commit/eeb3317b3dfc564485569db5b40319501b6ac4cb
      ```diff
      --- a/example/lib/location_callback_handler.dart
      +++ b/example/lib/location_callback_handler.dart
      @@ -4,25 +4,30 @@ import 'package:background_locator_2/location_dto.dart';
       
       import 'location_service_repository.dart';
       
      +@pragma('vm:entry-point')
       class LocationCallbackHandler {
      +  @pragma('vm:entry-point')
         static Future<void> initCallback(Map<dynamic, dynamic> params) async {
           LocationServiceRepository myLocationCallbackRepository =
               LocationServiceRepository();
           await myLocationCallbackRepository.init(params);
         }
       
      +  @pragma('vm:entry-point')
         static Future<void> disposeCallback() async {
           LocationServiceRepository myLocationCallbackRepository =
               LocationServiceRepository();
           await myLocationCallbackRepository.dispose();
         }
       
      +  @pragma('vm:entry-point')
         static Future<void> callback(LocationDto locationDto) async {
           LocationServiceRepository myLocationCallbackRepository =
               LocationServiceRepository();
           await myLocationCallbackRepository.callback(locationDto);
         }
       
      +  @pragma('vm:entry-point')
         static Future<void> notificationCallback() async {
           print('***notificationCallback');
         }
      ```
   - Referrences:
     - #46
     - https://github.com/firebase/flutterfire/issues/9446#issuecomment-1240554285
2. Run example app with release mode on Android device. (I am using Pixel5a (Android 13) device.)
   ```sh
   $ cd example
   $ flutter clean
   $ flutter pub get
   $ flutter run --release
   ```

---

This PR fixes the issue by changing data type from `LocationDto` to JSON(`Map<dynamic, dynamic>`) when sending data from background isolate to main isolate.
- last commit diff: https://github.com/Yukams/background_locator_fixed/commit/3e0e4dcad802b5122d480c940e391c4b518a4f45

I also make some changes:
- Upgrade kotlin and gradle versions for Android Studio: https://github.com/Yukams/background_locator_fixed/commit/272ff655bd4c21505597839d8fd295ae02bf42a5
- Support null safety for callback handler: https://github.com/Yukams/background_locator_fixed/commit/8f00532cf0a2ddd492e44d4aa12530feeec4f9b6

### CODE REVIEW

**Comment by garv-shah** [comment]
works perfectly for me too!

**Comment by n0tc0ding** [comment]
Doesnt seems to be working on 3.3.10 and 3.7.0.

I didnt check the changes and compare them to this PR but glofru PR works (didnt test on iOS):

background_locator:
    git:
      url: https://github.com/glofru/background_locator.git

**Comment by tulioccalazans** [comment]
It need to be merged!

**Comment by sanak** [comment]
@Yukams (CC: @moovida)
Thanks for merge this PR!

**Comment by Yukams** [comment]
Thank you very much @sanak, could you check the other PRs and tell me if you think they're worthy of being merged ?

**Comment by sanak** [comment]
> Thank you very much @sanak, could you check the other PRs and tell me if you think they're worthy of being merged ?

Sorry for late reply.
I think that another remaining PR seems to be a feature request.
Anyway, I still haven't checked new 2.0.6 release, so I will check it a bit with the latest Flutter version in this weekend.

**Comment by AbiezerLopezgh** [comment]
I was facing this issue, Flutter version 3.7.7 : "Unhandled Exception: Invalid argument: is a regular instance: Instance of 'LocationDto'", and as @sanak said, just had to format it into a Json, **locationDto.toJson()**.

**Pull request merged**
