### PR TITLE
Possible fix for callback not called

### PR DESCRIPTION
**Pull request by mohammedX6**
Possible fix for this issue: https://github.com/Yukams/background_locator_fixed/issues/41

`firebase_messaging` library has the same problem on Flutter 3.3.0
This is untested please test it before the merge.
Thanks

### CODE REVIEW

**Comment by alpapado** [comment]
This doesn't seem to solve the issue for me

**Comment by shantaly** [comment]
This fix seems to fix location service shutting down in the background but the port callback function registered to the isolate on the consuming app is still not getting called on IOS and Android

**Comment by mohammedX6** [comment]
> @alpapado another solution: on your method that starts background_locater (the one that starts the Isolate), please add this annotation `@pragma('vm:entry-point')`
@shantaly Hi, Please try this fix

**Comment by srmanc** [comment]
@shantaly @mohammedX6 You have to supply `@pragma('vm:entry-point')` above every top level or static function you wish to invoke outside of dart context. In this case there are two functions - the initial callback and the location callback.

I will correct the README and the HOW TO's to reflect what needs to be done for flutter 3.x support.

**Pull request closed without merging**
