### PR TITLE
iOS build fix

### PR DESCRIPTION
**Pull request by srmanc**
This PR addresses this issue: https://github.com/Yukams/background_locator_fixed/issues/29

There was a missing podspec file that has broken the iOS build.

### CODE REVIEW

**Review by Haris2v — APPROVED** [review]

**Comment by srmanc** [comment]
@Yukams Can we get this PR merged and pushed to pub.dev?

**Comment by srmanc** [comment]
@Yukams @Haris2v Any update on this? Sorry to push, I'm looking to using this plugin from upstream as soon as possible. Thanks for taking a look.

**Comment by srmanc** [comment]
Or if @Yukams you would consider adding me as a co-maintainer to this repository, I'd be more than glad to help to support and develop this plugin.

The plugin is basically a backbone for one of our apps and thus very important, I have great interest in supporting this.

**Comment by srmanc** [comment]
Or if @Yukams you would consider adding me as a co-maintainer to this repository, I'd be more than glad to help to support and develop this plugin.

The plugin is basically a backbone for one of our apps and thus very important, I have great interest in supporting this.

**Comment by Yukams** [comment]
@srmanc hi, you're welcome ! Thanks for taking time to work on this project. Merging should be good by now

**Comment by Yukams** [comment]
Though if you find time, could you keep the CHANGELOG file updated when merging branches to Master please ?

**Comment by srmanc** [comment]
@Yukams happy to do it.

I will take care of the CHANGELOG and update it. I also plan to update README to address changes on how to use the library after flutter 3.x obfuscation issues.

How about publishing to pub.dev? I can take care of tagging and docs, will you be able to publish versions or do you want to share that access as well?

**Comment by Yukams** [comment]
I'd say its better for the maintainer to be able to push it himself to pub.dev but I don't know how to share pub.dev yet, nor if it is possible

**Comment by Yukams** [comment]
I can invite you to pub.dev I just need your email

**Comment by srmanc** [comment]
It's irmancnik@gmail.com

**Comment by Yukams** [comment]
Alright it's done

**Pull request merged**
